//
// Created by nikita on 27.11.2019.
//

#ifndef LAB6_GRAMMAR_SYMBOLS_H
#define LAB6_GRAMMAR_SYMBOLS_H

enum GRAMMAR_SYMBOL_TYPE {
    WHILE, IF, ELSE, ASSIGNMENT, ERROR, BLOCK
};

#endif //LAB6_GRAMMAR_SYMBOLS_H
